### ISSUE TITLE
Not working with IELM, Eshell and probably other comint-derived modes

### ISSUE THREAD

**Issue by mekeor** [tarsius/orglink#14]
Hello Jonas,

with `emacs -q`,

- if you type `M-x ielm RET` followed by `M-x orglink-mode RET`, it is not possible to type anything into the prompt;
- and the same holds for `M-x eshell RET`.
- It seems likely that other comint-derived major-modes are affected too.

Instead of inserting the input, this is echoed: `funcall-interactively: Text is read-only`.

Thankfully,
Mekeor

**Comment by tarsius** [comment]
Well, this is intended for file-visiting buffers or other buffers that how "documents" of some sort. Shells, Repls and what not, is not really what I intend to support here. Could you please provide an example of when that would be useful?

**Comment by mekeor** [comment]
I think the main use-case is that simple URLs like `https://gnu.org` also match the Org link syntax and are made openable/clickable links by Orglink. Sometimes, such URLs will occur in Shells or IELM, and I'd like to be able to open/click them. To be fair, I could also use `goto-address-mode` instead. What do you think? Is this the scope of Orglink?

Thanks already.

**Comment by mekeor** [comment]
Alright, thanks.
