### ISSUE TITLE
defvar-keymap is not defined

### ISSUE THREAD

**Issue by Fuco1** [tarsius/orglink#15]
I have Emacs 28.2 and this doesn't seem to be installed, even with the `compat` dependency which I assume is a polyfill for the future API.

**Comment by tarsius** [comment]
Yes it's a pollyfill, and it is supposed to provide this function. Make sure you have at least Compat 29.1.0.0 installed. If that's already the case, we'll have to ask it's maintainer for help.

**Comment by Fuco1** [comment]
Yes, I had a bit older version.  Sorry for wasting your time and not double-checking :man_facepalming:
