### ISSUE TITLE
How about org-links in org-babel source code blocks?

### ISSUE THREAD

**Issue by madorian** [tarsius/orglink#16]
Would it be possible to work inside org-babel?;)

**Comment by tarsius** [comment]
You can use the commands `org-insert-link-global` and `org-open-at-point-global` inside code-blocks, but you'll have to add your own bindings (in `global-map` or `org-mode-map`).

The links are not fontified, which is a bit unfortunate.

I do not plan to add explicit support to overcome these limitations.
