### ISSUE TITLE
Links that are not links

### ISSUE THREAD

**Issue by michael-heerdegen** [tarsius/orglink#3]
I'm new to this mode.  I quite like it, but I get several parts of elisp code linkified that are not links.  For example:

    (put-alist 'org-bbdb-anniversary-format-alist "obit"
	       (lambda (name years suffix)
		 (concat "[[bbdb:" name "][" name "'s "
			 (number-to-string years)
			 suffix " obit]]")))

or

    (looking-back "^[[:space:]]*")

This is a bit annoying.  Is it useful at all to search for links in code (i.e. outside of comments?).  It is quite easy to test whether a certain POS is inside a comment by checking

    (nth 4 (syntax-ppss pos))

After running `org-activate-*-links you could run through the buffer a second time, looking for property org-link, and remove those org-link propertizations that are outside of comments.

**Comment by tarsius** [comment]
Okay so it took me a while but I just taught this package not to look for links in non-doc-string strings ;-)

**Comment by michael-heerdegen** [comment]
Thank you!
