### ISSUE TITLE
turn-on-orglink-mode-if-desired: Symbol’s value as variable is void: org-link-descriptive

### ISSUE THREAD

**Issue by 717g301github** [tarsius/orglink#8]
When attempting to M-x global-orglink-mode this is error that I get:

turn-on-orglink-mode-if-desired: Symbol’s value as variable is void: org-link-descriptive

Using Emacs from git:

GNU Emacs 27.0.50 (build 5, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2019-09-07

**Comment by tarsius** [comment]
Duplicate of #6.
